package com.ibam.granat.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

/**
 * Data Transfer Object (DTO) designed to handle data related to result generated by Customer Info request
 * while working with controllers and services.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
@ApiModel(value = "Customer Info Result", description = "Object considered for payment details specific for customer.")
public class CustomerInfoResultDTO {

    /**
     * Field considered for the name of the customer.
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    @ApiModelProperty(example = "Natiq Cəfərli Niyazi", value = "Field considered for the name of the customer.")
    private String customer;

    /**
     * Field considered for the id of the merchant that returned the customer information.
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY, value = "merchant_id")
    @ApiModelProperty(example = "44",
            value = "Field considered for the id of the merchant that returned the customer information.")
    private Long merchantId;


    /**
     * Field considered for the transaction id generated for specific payment.
     */
    @JsonProperty(access = JsonProperty.Access.READ_ONLY, value = "transaction_id")
    @ApiModelProperty(example = "80525020200325010350345408199",
            value = "Field considered for the transaction id generated for specific payment.")
    private String transactionId;

    /**
     * Field considered for the billing operations that customer is able to do.
     * Since there are several details related to billing operation,
     * they are collected in <code>BillingOperation</code>.
     *
     * @see BillingOperation
     */
    @JsonProperty(value = "billing_operations")
    @ApiModelProperty(value = "Field considered for the billing operations that customer is able to do.")
    private List<BillingOperation> billingOperations;


    @JsonProperty(value = "abonent_code")
    @ApiModelProperty(value = "Field considered for the abonent code")
    private String abonentCode;

//    @JsonProperty(value = "service_groups")
//    @ApiModelProperty(value = "Field considered for the  groups of pre paid services")
//    private List<PrePayServiceGroup> serviceGroups;

//    @JsonProperty(value = "payment_receivers")
//    @ApiModelProperty(value = "Field considered for the receivers of payment")
//    @JsonSetter(nulls = Nulls.AS_EMPTY)
//    private List<PaymentReceiverDTO> paymentReceivers;

//    @JsonProperty(value = "items")
//    @ApiModelProperty(value = "Field considered for key value front of payment")
//    private List<ItemDTO> items;
//
//    @JsonProperty(value = "result_details")
//    @ApiModelProperty(value = "Field considered for key value front of payment")
//    private CategoryConfigDTO resultDetails;

//    @JsonProperty(value = "pay_details")
//    @ApiModelProperty(value = "Field considered for key value front of payment")
//    private PayDetailConfigDTO payDetails;

}
