package com.ibam.granat.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) designed to handle any response generated by microservice
 * while working with controllers and services.
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
@ApiModel(value = "Response",
        description = "Object considered to be a wrapper for any response that is required to be returned.")
public class ResponseDTO<T> implements Serializable {
    /**
     * Field considered to keep response returned by requested operation.
     */
    @ApiModelProperty(value = "Field considered to keep response returned by requested operation.")
    private T data;


    /**
     * Field considered to describe message of the response returned.
     */
    @Builder.Default
    @ApiModelProperty(example = "Success", value = "Field considered to describe message of the response returned.")
    private String message = "Success";
}
